/*
NetBox API

API to access NetBox

API version: 2.11
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// Type6 struct for Type6
type Type6 struct {
	Label string `json:"label"`
	Value string `json:"value"`
}

// NewType6 instantiates a new Type6 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewType6(label string, value string) *Type6 {
	this := Type6{}
	this.Label = label
	this.Value = value
	return &this
}

// NewType6WithDefaults instantiates a new Type6 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewType6WithDefaults() *Type6 {
	this := Type6{}
	return &this
}

// GetLabel returns the Label field value
func (o *Type6) GetLabel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Label
}

// GetLabelOk returns a tuple with the Label field value
// and a boolean to check if the value has been set.
func (o *Type6) GetLabelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Label, true
}

// SetLabel sets field value
func (o *Type6) SetLabel(v string) {
	o.Label = v
}

// GetValue returns the Value field value
func (o *Type6) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *Type6) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *Type6) SetValue(v string) {
	o.Value = v
}

func (o Type6) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["label"] = o.Label
	}
	if true {
		toSerialize["value"] = o.Value
	}
	return json.Marshal(toSerialize)
}

type NullableType6 struct {
	value *Type6
	isSet bool
}

func (v NullableType6) Get() *Type6 {
	return v.value
}

func (v *NullableType6) Set(val *Type6) {
	v.value = val
	v.isSet = true
}

func (v NullableType6) IsSet() bool {
	return v.isSet
}

func (v *NullableType6) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableType6(val *Type6) *NullableType6 {
	return &NullableType6{value: val, isSet: true}
}

func (v NullableType6) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableType6) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


