/*
NetBox API

API to access NetBox

API version: 2.11
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// Type7 struct for Type7
type Type7 struct {
	Label string `json:"label"`
	Value string `json:"value"`
}

// NewType7 instantiates a new Type7 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewType7(label string, value string) *Type7 {
	this := Type7{}
	this.Label = label
	this.Value = value
	return &this
}

// NewType7WithDefaults instantiates a new Type7 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewType7WithDefaults() *Type7 {
	this := Type7{}
	return &this
}

// GetLabel returns the Label field value
func (o *Type7) GetLabel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Label
}

// GetLabelOk returns a tuple with the Label field value
// and a boolean to check if the value has been set.
func (o *Type7) GetLabelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Label, true
}

// SetLabel sets field value
func (o *Type7) SetLabel(v string) {
	o.Label = v
}

// GetValue returns the Value field value
func (o *Type7) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *Type7) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *Type7) SetValue(v string) {
	o.Value = v
}

func (o Type7) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["label"] = o.Label
	}
	if true {
		toSerialize["value"] = o.Value
	}
	return json.Marshal(toSerialize)
}

type NullableType7 struct {
	value *Type7
	isSet bool
}

func (v NullableType7) Get() *Type7 {
	return v.value
}

func (v *NullableType7) Set(val *Type7) {
	v.value = val
	v.isSet = true
}

func (v NullableType7) IsSet() bool {
	return v.isSet
}

func (v *NullableType7) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableType7(val *Type7) *NullableType7 {
	return &NullableType7{value: val, isSet: true}
}

func (v NullableType7) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableType7) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


