/*
NetBox API

API to access NetBox

API version: 2.11
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// Type5 struct for Type5
type Type5 struct {
	Label string `json:"label"`
	Value string `json:"value"`
}

// NewType5 instantiates a new Type5 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewType5(label string, value string) *Type5 {
	this := Type5{}
	this.Label = label
	this.Value = value
	return &this
}

// NewType5WithDefaults instantiates a new Type5 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewType5WithDefaults() *Type5 {
	this := Type5{}
	return &this
}

// GetLabel returns the Label field value
func (o *Type5) GetLabel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Label
}

// GetLabelOk returns a tuple with the Label field value
// and a boolean to check if the value has been set.
func (o *Type5) GetLabelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Label, true
}

// SetLabel sets field value
func (o *Type5) SetLabel(v string) {
	o.Label = v
}

// GetValue returns the Value field value
func (o *Type5) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *Type5) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *Type5) SetValue(v string) {
	o.Value = v
}

func (o Type5) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["label"] = o.Label
	}
	if true {
		toSerialize["value"] = o.Value
	}
	return json.Marshal(toSerialize)
}

type NullableType5 struct {
	value *Type5
	isSet bool
}

func (v NullableType5) Get() *Type5 {
	return v.value
}

func (v *NullableType5) Set(val *Type5) {
	v.value = val
	v.isSet = true
}

func (v NullableType5) IsSet() bool {
	return v.isSet
}

func (v *NullableType5) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableType5(val *Type5) *NullableType5 {
	return &NullableType5{value: val, isSet: true}
}

func (v NullableType5) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableType5) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


