/*
NetBox API

API to access NetBox

API version: 2.11
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
)

// Phase struct for Phase
type Phase struct {
	Label string `json:"label"`
	Value string `json:"value"`
}

// NewPhase instantiates a new Phase object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPhase(label string, value string) *Phase {
	this := Phase{}
	this.Label = label
	this.Value = value
	return &this
}

// NewPhaseWithDefaults instantiates a new Phase object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPhaseWithDefaults() *Phase {
	this := Phase{}
	return &this
}

// GetLabel returns the Label field value
func (o *Phase) GetLabel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Label
}

// GetLabelOk returns a tuple with the Label field value
// and a boolean to check if the value has been set.
func (o *Phase) GetLabelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Label, true
}

// SetLabel sets field value
func (o *Phase) SetLabel(v string) {
	o.Label = v
}

// GetValue returns the Value field value
func (o *Phase) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *Phase) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *Phase) SetValue(v string) {
	o.Value = v
}

func (o Phase) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["label"] = o.Label
	}
	if true {
		toSerialize["value"] = o.Value
	}
	return json.Marshal(toSerialize)
}

type NullablePhase struct {
	value *Phase
	isSet bool
}

func (v NullablePhase) Get() *Phase {
	return v.value
}

func (v *NullablePhase) Set(val *Phase) {
	v.value = val
	v.isSet = true
}

func (v NullablePhase) IsSet() bool {
	return v.isSet
}

func (v *NullablePhase) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePhase(val *Phase) *NullablePhase {
	return &NullablePhase{value: val, isSet: true}
}

func (v NullablePhase) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePhase) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


