/*
NetBox API

API to access NetBox

API version: 2.11
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"time"
)

// Manufacturer struct for Manufacturer
type Manufacturer struct {
	Id *int32 `json:"id,omitempty"`
	Url *string `json:"url,omitempty"`
	Display *string `json:"display,omitempty"`
	Name string `json:"name"`
	Slug string `json:"slug"`
	Description *string `json:"description,omitempty"`
	CustomFields map[string]interface{} `json:"custom_fields,omitempty"`
	Created *string `json:"created,omitempty"`
	LastUpdated *time.Time `json:"last_updated,omitempty"`
	DevicetypeCount *int32 `json:"devicetype_count,omitempty"`
	InventoryitemCount *int32 `json:"inventoryitem_count,omitempty"`
	PlatformCount *int32 `json:"platform_count,omitempty"`
}

// NewManufacturer instantiates a new Manufacturer object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewManufacturer(name string, slug string) *Manufacturer {
	this := Manufacturer{}
	this.Name = name
	this.Slug = slug
	return &this
}

// NewManufacturerWithDefaults instantiates a new Manufacturer object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewManufacturerWithDefaults() *Manufacturer {
	this := Manufacturer{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Manufacturer) GetId() int32 {
	if o == nil || o.Id == nil {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Manufacturer) GetIdOk() (*int32, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *Manufacturer) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *Manufacturer) SetId(v int32) {
	o.Id = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *Manufacturer) GetUrl() string {
	if o == nil || o.Url == nil {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Manufacturer) GetUrlOk() (*string, bool) {
	if o == nil || o.Url == nil {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *Manufacturer) HasUrl() bool {
	if o != nil && o.Url != nil {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *Manufacturer) SetUrl(v string) {
	o.Url = &v
}

// GetDisplay returns the Display field value if set, zero value otherwise.
func (o *Manufacturer) GetDisplay() string {
	if o == nil || o.Display == nil {
		var ret string
		return ret
	}
	return *o.Display
}

// GetDisplayOk returns a tuple with the Display field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Manufacturer) GetDisplayOk() (*string, bool) {
	if o == nil || o.Display == nil {
		return nil, false
	}
	return o.Display, true
}

// HasDisplay returns a boolean if a field has been set.
func (o *Manufacturer) HasDisplay() bool {
	if o != nil && o.Display != nil {
		return true
	}

	return false
}

// SetDisplay gets a reference to the given string and assigns it to the Display field.
func (o *Manufacturer) SetDisplay(v string) {
	o.Display = &v
}

// GetName returns the Name field value
func (o *Manufacturer) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *Manufacturer) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *Manufacturer) SetName(v string) {
	o.Name = v
}

// GetSlug returns the Slug field value
func (o *Manufacturer) GetSlug() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Slug
}

// GetSlugOk returns a tuple with the Slug field value
// and a boolean to check if the value has been set.
func (o *Manufacturer) GetSlugOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Slug, true
}

// SetSlug sets field value
func (o *Manufacturer) SetSlug(v string) {
	o.Slug = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *Manufacturer) GetDescription() string {
	if o == nil || o.Description == nil {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Manufacturer) GetDescriptionOk() (*string, bool) {
	if o == nil || o.Description == nil {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *Manufacturer) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *Manufacturer) SetDescription(v string) {
	o.Description = &v
}

// GetCustomFields returns the CustomFields field value if set, zero value otherwise.
func (o *Manufacturer) GetCustomFields() map[string]interface{} {
	if o == nil || o.CustomFields == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.CustomFields
}

// GetCustomFieldsOk returns a tuple with the CustomFields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Manufacturer) GetCustomFieldsOk() (map[string]interface{}, bool) {
	if o == nil || o.CustomFields == nil {
		return nil, false
	}
	return o.CustomFields, true
}

// HasCustomFields returns a boolean if a field has been set.
func (o *Manufacturer) HasCustomFields() bool {
	if o != nil && o.CustomFields != nil {
		return true
	}

	return false
}

// SetCustomFields gets a reference to the given map[string]interface{} and assigns it to the CustomFields field.
func (o *Manufacturer) SetCustomFields(v map[string]interface{}) {
	o.CustomFields = v
}

// GetCreated returns the Created field value if set, zero value otherwise.
func (o *Manufacturer) GetCreated() string {
	if o == nil || o.Created == nil {
		var ret string
		return ret
	}
	return *o.Created
}

// GetCreatedOk returns a tuple with the Created field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Manufacturer) GetCreatedOk() (*string, bool) {
	if o == nil || o.Created == nil {
		return nil, false
	}
	return o.Created, true
}

// HasCreated returns a boolean if a field has been set.
func (o *Manufacturer) HasCreated() bool {
	if o != nil && o.Created != nil {
		return true
	}

	return false
}

// SetCreated gets a reference to the given string and assigns it to the Created field.
func (o *Manufacturer) SetCreated(v string) {
	o.Created = &v
}

// GetLastUpdated returns the LastUpdated field value if set, zero value otherwise.
func (o *Manufacturer) GetLastUpdated() time.Time {
	if o == nil || o.LastUpdated == nil {
		var ret time.Time
		return ret
	}
	return *o.LastUpdated
}

// GetLastUpdatedOk returns a tuple with the LastUpdated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Manufacturer) GetLastUpdatedOk() (*time.Time, bool) {
	if o == nil || o.LastUpdated == nil {
		return nil, false
	}
	return o.LastUpdated, true
}

// HasLastUpdated returns a boolean if a field has been set.
func (o *Manufacturer) HasLastUpdated() bool {
	if o != nil && o.LastUpdated != nil {
		return true
	}

	return false
}

// SetLastUpdated gets a reference to the given time.Time and assigns it to the LastUpdated field.
func (o *Manufacturer) SetLastUpdated(v time.Time) {
	o.LastUpdated = &v
}

// GetDevicetypeCount returns the DevicetypeCount field value if set, zero value otherwise.
func (o *Manufacturer) GetDevicetypeCount() int32 {
	if o == nil || o.DevicetypeCount == nil {
		var ret int32
		return ret
	}
	return *o.DevicetypeCount
}

// GetDevicetypeCountOk returns a tuple with the DevicetypeCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Manufacturer) GetDevicetypeCountOk() (*int32, bool) {
	if o == nil || o.DevicetypeCount == nil {
		return nil, false
	}
	return o.DevicetypeCount, true
}

// HasDevicetypeCount returns a boolean if a field has been set.
func (o *Manufacturer) HasDevicetypeCount() bool {
	if o != nil && o.DevicetypeCount != nil {
		return true
	}

	return false
}

// SetDevicetypeCount gets a reference to the given int32 and assigns it to the DevicetypeCount field.
func (o *Manufacturer) SetDevicetypeCount(v int32) {
	o.DevicetypeCount = &v
}

// GetInventoryitemCount returns the InventoryitemCount field value if set, zero value otherwise.
func (o *Manufacturer) GetInventoryitemCount() int32 {
	if o == nil || o.InventoryitemCount == nil {
		var ret int32
		return ret
	}
	return *o.InventoryitemCount
}

// GetInventoryitemCountOk returns a tuple with the InventoryitemCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Manufacturer) GetInventoryitemCountOk() (*int32, bool) {
	if o == nil || o.InventoryitemCount == nil {
		return nil, false
	}
	return o.InventoryitemCount, true
}

// HasInventoryitemCount returns a boolean if a field has been set.
func (o *Manufacturer) HasInventoryitemCount() bool {
	if o != nil && o.InventoryitemCount != nil {
		return true
	}

	return false
}

// SetInventoryitemCount gets a reference to the given int32 and assigns it to the InventoryitemCount field.
func (o *Manufacturer) SetInventoryitemCount(v int32) {
	o.InventoryitemCount = &v
}

// GetPlatformCount returns the PlatformCount field value if set, zero value otherwise.
func (o *Manufacturer) GetPlatformCount() int32 {
	if o == nil || o.PlatformCount == nil {
		var ret int32
		return ret
	}
	return *o.PlatformCount
}

// GetPlatformCountOk returns a tuple with the PlatformCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Manufacturer) GetPlatformCountOk() (*int32, bool) {
	if o == nil || o.PlatformCount == nil {
		return nil, false
	}
	return o.PlatformCount, true
}

// HasPlatformCount returns a boolean if a field has been set.
func (o *Manufacturer) HasPlatformCount() bool {
	if o != nil && o.PlatformCount != nil {
		return true
	}

	return false
}

// SetPlatformCount gets a reference to the given int32 and assigns it to the PlatformCount field.
func (o *Manufacturer) SetPlatformCount(v int32) {
	o.PlatformCount = &v
}

func (o Manufacturer) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.Url != nil {
		toSerialize["url"] = o.Url
	}
	if o.Display != nil {
		toSerialize["display"] = o.Display
	}
	if true {
		toSerialize["name"] = o.Name
	}
	if true {
		toSerialize["slug"] = o.Slug
	}
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	if o.CustomFields != nil {
		toSerialize["custom_fields"] = o.CustomFields
	}
	if o.Created != nil {
		toSerialize["created"] = o.Created
	}
	if o.LastUpdated != nil {
		toSerialize["last_updated"] = o.LastUpdated
	}
	if o.DevicetypeCount != nil {
		toSerialize["devicetype_count"] = o.DevicetypeCount
	}
	if o.InventoryitemCount != nil {
		toSerialize["inventoryitem_count"] = o.InventoryitemCount
	}
	if o.PlatformCount != nil {
		toSerialize["platform_count"] = o.PlatformCount
	}
	return json.Marshal(toSerialize)
}

type NullableManufacturer struct {
	value *Manufacturer
	isSet bool
}

func (v NullableManufacturer) Get() *Manufacturer {
	return v.value
}

func (v *NullableManufacturer) Set(val *Manufacturer) {
	v.value = val
	v.isSet = true
}

func (v NullableManufacturer) IsSet() bool {
	return v.isSet
}

func (v *NullableManufacturer) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManufacturer(val *Manufacturer) *NullableManufacturer {
	return &NullableManufacturer{value: val, isSet: true}
}

func (v NullableManufacturer) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManufacturer) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


